# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
