# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'dateCreated'},
        ),
    ]
