# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170724_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-dateCreated', '-dateUpdated']},
        ),
    ]
