# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170724_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateUpdated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
