# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170724_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=1989, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=1998, max_length=50),
            preserve_default=False,
        ),
    ]
